services:
  - type: web
    name: hianimez
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: DB_HOSTSEG
      - key: DB_USERSEG
      - key: DB_PASSSEG
      - key: DB_NAMESEG
      - key: CONTACT_EMAIL
