services:
  - type: web
    name: hianime-render-app
    runtime: docker
    repo: https://github.com/Vickydmt/hianime-render
    branch: main
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: DB_HOSTSEG
        sync: false
      - key: DB_USERSEG
        sync: false
      - key: DB_PASSSEG
        sync: false
      - key: DB_NAMESEG
        sync: false
      - key: CONTACT_EMAIL
        sync: false
