services:
  - type: web
    name: hianimez
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: DB_HOSTSEG
        value: placeholder_change_me
      - key: DB_USERSEG
        value: placeholder_change_me
      - key: DB_PASSSEG
        value: placeholder_change_me
      - key: DB_NAMESEG
        value: placeholder_change_me
      - key: CONTACT_EMAIL
        value: placeholder_change_me
